app = "we-bot"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "node src/index.js"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  NODE_ENV = "production" 