app = "football-ticket-bot"
primary_region = "lax"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  HEADLESS = "true"
  SLOW_MO = "50"
  REFRESH_INTERVAL = "60000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[processes]
  web = "node src/index.js" 